### ISSUE TITLE
Feature: Add Status Notices & Standardize Framework Frontmatter

### ISSUE THREAD

**Issue by GlobalGovernanceFramework** [GlobalGovernanceFrameworks/website#8]
### Description

To improve site-wide consistency and user trust, this issue combines two related tasks:
1.  **Adding development status notices:** To transparently communicate that the website is an active, ongoing project with some areas still under revision. This manages user expectations and frames the content correctly.
2.  **Standardizing framework metadata:** To ensure that all core framework documents use a consistent, machine-readable frontmatter structure. This is crucial for maintainability and for potentially displaying metadata dynamically on the site.

**User Stories:**
> As a potential founder, I want to understand that the site is a living project so I can focus on the core vision and not be deterred by minor imperfections.

> As a developer/maintainer, I want all framework documents to use a consistent metadata structure so that I can manage them efficiently and build features based on that data.

### Acceptance Criteria

1.  **Site-Wide Banner:**
    * A reusable Svelte component named `GlobalNotice.svelte` is created.
    * This component displays a brief, site-wide message about the project's development status.
    * The component is added to the main layout file (`src/routes/+layout.svelte`) so it appears at the top of every page.
    * The banner should be dismissible (e.g., with an 'x' button that hides it for the session).

2.  **Section-Specific Notice:**
    * A second reusable component named `SectionNotice.svelte` is created for more detailed messages.
    * An instance of `SectionNotice.svelte` is added to the top of the main frameworks page (`src/routes/frameworks/+page.svelte`).

3.  **Decommission Homepage Disclaimer:**
    * The existing "Framework Development Status" accordion on the homepage (`/`) will be removed to avoid redundancy with the new site-wide banner.

4.  **Standardize Framework Frontmatter:**
    * All primary framework files (e.g., `frameworks/ai-futures/index.md`, `frameworks/climate-and-energy-governance/index.md`, etc.) must be reviewed.
    * Their frontmatter must be updated to include the consistent set of fields defined in the implementation details below. This ensures all frameworks have uniform, machine-readable metadata. Section-level files (e.g., `principles.md`) are out of scope for this part of the task.

### Implementation Details & Content

**1. `GlobalNotice.svelte` Component**
* **Wording:** "This is a living project. We are actively developing these frameworks and building our organization. You may encounter broken links or inconsistencies. Thank you for your understanding."
* **Example Code:**
    ```svelte
    <script>
      import { onMount } from 'svelte';
      let visible = false;
      onMount(() => {
        if (!sessionStorage.getItem('noticeDismissed')) { visible = true; }
      });
      function dismiss() {
        sessionStorage.setItem('noticeDismissed', 'true');
        visible = false;
      }
    </script>
    {#if visible}
      <div class="bg-blue-100 border-b border-blue-200 text-blue-800 text-center p-2 relative text-sm">
        <span>This is a living project. We are actively developing these frameworks and building our organization. You may encounter broken links or inconsistencies. Thank you for your understanding.</span>
        <button on:click={dismiss} class="absolute top-0 right-0 p-2 font-bold" aria-label="Dismiss">&times;</button>
      </div>
    {/if}
    ```

**2. `SectionNotice.svelte` Component**
* **Wording (for Frameworks page):** "Note from the Founder: This section is currently undergoing a significant revision to improve clarity and consistency. The core ideas are present, but we are actively working on refining the content. Your feedback during this stage is invaluable."
* **Example Code:**
    ```svelte
    <div class="border-l-4 border-yellow-400 bg-yellow-50 p-4 my-6" role="alert">
      <p class="font-bold">A Note on This Section</p>
      <p><slot>Default notice content goes here.</slot></p>
    </div>
    ```

**3. Standard Framework Frontmatter Template**
This structure should be applied to the primary `index.md` file of each framework.

* **Template:**
    ```yaml
    ---
    # The full, human-readable name of the framework.
    title: "Example Framework Title"
    
    # The current maturity level. (e.g., 'Draft', 'Enhanced Version', 'Community Review')
    status: "Enhanced Version"
    
    # The date of the last modification in YYYY-MM-DD format.
    lastUpdated: "2025-06-24"
    
    # The major/minor version number.
    revision: "1.1"
    
    # The release date of the current revision in YYYY-MM-DD format.
    releaseDate: "2025-06-20"
    
    # The planned date for the next major review, or "To be determined".
    nextReview: "2026-06-01"
    ---
    ```
